### PR TITLE
Show symbol type on hover

### PR DESCRIPTION
**Pull request by patrys**
I'm playing with the idea of providing type annotations on hover instead of duplicating autocomplete results. This is quite useful especially when combined with PEP 484 annotations or comments with type hints.

### CODE REVIEW

**Comment by patrys** [comment]
I think this is ready for review now. The behaviour is as follows:

* for classes and functions hover displays the docstring (if available) and the signature
* for modules hover displays the docstring (if available) and the full name
* for the rest (mostly variables) hover shows possible types inferred by jedi

**Comment by gandhis1** [comment]
Any screenshots?

**Comment by patrys** [comment]
Variable:
image

Function:
image

**Comment by gandhis1** [comment]
Looks great. Anything you can do to handle very long doc strings, like limiting the hover box height and adding a scroll bar, or is that limited by VS Code?

**Comment by patrys** [comment]
This is already handled by VS Code.

**Pull request merged**
