### PR TITLE
Pylama

### PR DESCRIPTION
**Pull request by tdamsma**
I tried to implement pylama (as requested [here](https://github.com/DonJayamanne/pythonVSCode/issues/482)) in a similar way as pep8. Unfortunately I can't get the current master to build on my system, so I haven't been able to test if it actually works

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@tdamsma 
You need to define the configuration settings in package.json as follows:
```json
        "python.linting.pylamaEnabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether to lint Python files using pylama."
        },
        "python.linting.pylamaPath": {
          "type": "string",
          "default": "pylama",
          "description": "Path to pylama, you can use a custom version of pylama by modifying this setting to include the full path."
        },
        "python.linting.pylamaArgs": {
          "type": "array",
          "description": "Arguments passed in. Each argument is a separate item in the array.",
          "default": [],
          "items": {
            "type": "string"
          }
        },
```

**Comment by DonJayamanne** [comment]
Please try to add some tests for the new linter in the ```test``` directory.
FYI - You'll need to update ```requirements.txt``` for tests to run on ```travis```

**Comment by tdamsma** [comment]
Thanks for accepting the PR, but I didn't have the chance to implement your suggestions. Should I put them in a new PR, or did you already fix it?

**Comment by DonJayamanne** [comment]
I made the necessary changes, thanks

**Pull request merged**
