### PR TITLE
Add pdb snippet

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@robsonpeixoto , not sure i want to add this into the list of snippets. This extension supports debugging without the use of pdb, i.e. people won't have to resort to the old pdb debugger when using this.
Just out of curiosity, under what circumstance are you using the pdb debugger and not the one built into this extension?

**Comment by robsonpeixoto** [comment]
No problem. I'm using on my snippets.
I'm using docker to run the service, so the pdb is very useful.

**Comment by DonJayamanne** [comment]
@robsonpeixoto , so there is a use case. Will add. Thanks

**Comment by DonJayamanne** [comment]
@robsonpeixoto , how do you use vscode with docker?
- does vscode provide intellisense, etc?
I don't think so. This is one area that needs to be improved (adding support for remote interpreters - docker)

**Comment by robsonpeixoto** [comment]
@DonJayamanne I'm creating a virtualenv with all deps to use the intellisense.
But I'm using a docker-compose with all env var configured making easier to run using docker.

But I agree with you, the pythonVSCode should support remote interpreters.

**Comment by robsonpeixoto** [comment]
And thanks for the attention

**Comment by DonJayamanne** [comment]
@robsonpeixoto , just out of curiosity doesn't [remote debugging](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging) help? or is it just a case of preference?

**Comment by robsonpeixoto** [comment]
Just case of preference. I'll study more about this plugin.

**Pull request merged**
