### PR TITLE
Fixes nose run test on test case

### LINKED ISSUE #597: 'Run Test' on TestCase class does not recognise test methods when using nose
## Environment data
VS Code version:  1.9.0-Insider
Python Extension version:  0.5.5
Python Version:   3.5.2
OS and version:    macos sierra 10.12.2beta
Your settings.json:   
```json
{  "python.unitTest.nosetestArgs": [
    "--with-xunit",
    "--xunit-file=${workspaceRoot}/nosetests.xml"
  ],
  "python.unitTest.nosetestsEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
E
======================================================================
ERROR: Failure: ValueError (No such test tests.test_class.TestABC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/____/anaconda/envs/microsvc/lib/python3.5/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
ValueError: No such test tests.test_class.TestABC

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```   

## Actual behavior
For the below test class, clicking 'Run Test' on the class fails with the above message. Nose is unable to recognise the two test methods included in the class.

```python
# tests/test_class.py
class TestABC(TestCase):
    """ testing """

    def test_ok(self):
        """ testing """
        self.assertTrue(1 == 1)

    def test_not_ok(self):
        """ testing False """
        self.assertFalse(1 == 2)
```
## Expected  behavior
Clicking 'Run Test' for the class should run the two test methods test_ok and test_not_ok.

## Steps to reproduce:  
-  create a test class as above
-  click on the 'Run Test' link for the class TestABC

### PR DESCRIPTION
**Pull request by efremovd**
Hi,

First, thank you for your awesome work.

Fixes #597

I went through doc for nose and looks like test should be run as `<file_name>:<class name>` so I fixed nameToRun to have such syntax.

### CODE REVIEW

**Comment by efremovd** [comment]
did they ever pass?

**Comment by DonJayamanne** [comment]
@efremovd 
I've tested the changes & it looks great. Unfortunately I too made some changes to this file.
Please could you resolve the conflicts so I can merge this in. 
Thanks.

**Comment by efremovd** [comment]
@DonJayamanne will do later today. Thank you.

**Comment by efremovd** [comment]
@DonJayamanne I resolved conflicts, please review. Thank you.

**Pull request merged**
