### PR TITLE
Rename launch config names for the debugger.

### PR DESCRIPTION
**Pull request by jackqq**
I found myself quite confused first trying to run the Python debugger of this extension in developing or debugging mode, until I read the "Development Setup for mock-debug" section in the doc page "Example - Debuggers" of VSCode.

So I'm trying to rename and comment the launch config of the debugger to make them easier for new contributors to understand.

### CODE REVIEW

**Comment by jackqq** [comment]
The debugging section of the wiki page 'Contribution' needs to be updated to this change. Would you please, or tell me how to do it?

**Comment by DonJayamanne** [comment]
@jackqq , done, thanks for the tip.
https://github.com/DonJayamanne/pythonVSCode/wiki/Contribution#debugging-the-python-extension-debugger

In the future please do try to add an issue for these. Its easier to track it, else i'll just forget these. For instance this PR was closed, hence will never re-visit them. Yes I do get the messages, however I forget them as well - the issues are a great way to keep track of "issues/requests" 👍

**Comment by jackqq** [comment]
All right! I'll track these with issues in the future. Thanks!

**Comment by DonJayamanne** [comment]
@jackqq , ensures that I don't miss/forget items. Thanks

**Pull request merged**
