### PR TITLE
Better formatting of docstring

### LINKED ISSUE #821: Common docstring formats are not displayed nicely in docstring hover pop-up
## Environment data
VS Code version:  1.10.2
Python Extension version:  6.0
Python Version:   3.5.3
OS and version:    OS X El Capitan Version 10.11.6

## Actual behavior
When you hover over a function call in your code, you get a small pop-up showing you the docstring of that function. Function signature is formatted nicely, and reStructured Text headers are respected, but elements such as parameter and/or return value names and types - as formatted according to common conventions such as [Numpy's](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt), [Google's](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) or [Sphnix](http://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html) - are shown in raw text form.

## Expected  behavior
Docstrings using the above format should be formatted nicely.

## Steps to reproduce:  
-  Write a docstring for a function in one of the following formats: Numpy, Google, Sphinx.
-  Hover over a call to that function.

## Comments
I don't know if this functionality comes from general VSCode code or this extension's code. In any case, I'd really appreciate getting a pointer to the right direction so I can attempt to contribute an implementation of this feature.

### PR DESCRIPTION
**Pull request by neilsustc**
'Translate' reStructuredText into Markdown. Fix #821.

### CODE REVIEW

**Comment by neilsustc** [comment]
Todos:

- [ ] change field list `:some_field:` to bold text
- [ ] remove indention in definition list

**Comment by 1st** [comment]
Looks good. But in my opinion, it will be fine to make headers much smaller, because white color already telling us tgat this is a header (like Examples, Returns, References)

**Comment by DonJayamanne** [comment]
@neilsustc Thanks for your work on this. Let me know when you are ready for me to merge something.

**Comment by DonJayamanne** [comment]
How about you get things working to a certain stage and we merge it.
I.e. merge incrementally...

**Comment by neilsustc** [comment]
I think the docs will look good in most cases now, especially for `numpy` and `sklearn`.

But there are some conflicts and failed tests, @DonJayamanne can you help fix them?

---

@1st I have set the headings to level 2 so they would become a bit smaller now.

**Comment by neilsustc** [comment]
@DonJayamanne All done!

**Comment by DonJayamanne** [comment]
Brilliant risk mate, will check this out tonight and release something soon.

**Comment by DonJayamanne** [comment]
@neilsustc , there are some conflicts in jediHelper.ts, please could you resolve them.

**Comment by neilsustc** [comment]
👌

**Comment by 1st** [comment]
Will be happy to test this new thing

**Pull request merged**
