### PR TITLE
#764 feature request: auto import

### PR DESCRIPTION
**Pull request by skyjur**
Please let me know what should be improved or if you have ideas how to do things better, and I will try to implement it. 

https://github.com/DonJayamanne/pythonVSCode/issues/764

autoimport

### CODE REVIEW

**Comment by skyjur** [comment]
I think I will update to make use of `isort -a` (https://github.com/timothycrosley/isort#adding-an-import-to-multiple-files)

**Comment by skyjur** [comment]
I've tried to make use of existing `importSortProvider.ts`, and refactored it to support `addImport()`.

Also, I have found the comment saying that `--diff` doesn't work together with passing code as stdin on `isort`, but in my testing it worked just fine. So I've updated to use stdin. I think it makes some things simpler as well as it should be more efficient than creating a temporary file.

As this is my first contribution I've tried to leave things as closely as they are.

Some tests were failing because the last line now is handled slightly differently and now in some
cases it doesn't produce a diff where it used to. I've refactored  out very long lines while working on fixing them.

**Comment by DonJayamanne** [comment]
Please could you revert the changes to PythonImportSortProvider that changes its behaviour. Lets leave this PR specific to just the auto import feature.
Please create a separate PR that makes changes to PythonImportSortProvider to improve it with the changes to the arguments, etc.
its easier to focus on one change at a time in each PR, easier for testing too.

**Comment by DonJayamanne** [comment]
Oh yes, thanks for the great work.

**Comment by skyjur** [comment]
I've removed the changes I did for the import-sort part and added a few tests.

I have tried using it for a while, and I found that, at least for me it was very inconvenient to have sorter attached to auto-import, sometimes I didn't want to sort imports and was no way out of it.

**Comment by skyjur** [comment]
Anything else I can do to improve this?

**Comment by skyjur** [comment]
Anything else I can do to improve this?

**Comment by DonJayamanne** [comment]
damn, forgot about this. Will look into this tomorrow and release this soon.
Unfortunately I released a new version a moment ago. Sorry, thanks again for your great effort. I've been wanting to work on an auto import. Please hang in there, i'll release this soon.

And thanks for the unit tests

**Comment by DonJayamanne** [comment]
Unfortunately this doesn't always work.
I've tested this. It works only when the editor is able to resolve references, and I don't believe that'll work majority of the time.
I should have informed you about this earlier, but I will be reverting the change.

**Comment by skyjur** [comment]
>  It works only when the editor is able to resolve references

Yes, but would could be done if reference cannot be resolved?

**Comment by DonJayamanne** [comment]
>>Yes, but would could be done if reference cannot be resolved?

Sorry, didn't follow you here.

**Comment by DonJayamanne** [comment]
Check whether the following gives you what you need: https://github.com/markbaas/python-iresolve

**Comment by skyjur** [comment]
I think it is best to use workspace-symbol-lookup to implement this feature.

If symbol lookup as currently is implemented does not find symbols in majority of cases, then I think it's better to improve on symbol lookup, instead of using alternative symbol-resolver just for auto-import capability.

**Comment by skyjur** [comment]
I will have a look however, into iresolve in following few days to see if it can work better than ctags.

**Comment by DonJayamanne** [comment]
Symbol lookup cannot work the way you suggest. First the code needs to tell the ide what it is using before the ide can figure it out for itself. It can't think for the user.

What if your are using a method that exists on two separate modules? Which one do you want to use?

**Comment by DonJayamanne** [comment]
Also the symbol lookup is provided by the python library Jedi

**Comment by skyjur** [comment]
> What if your are using a method that exists on two separate modules? Which one do you want to use?

It shows a quick-pick menu with all modules.

> Also the symbol lookup is provided by the python library Jedi

Just to clarify, I think for auto-import suitable lookup is workspace-symbol-lookup
Jedi is used for active editor symbol-lookup. However this is limited to only symbols that already had been imported and can be resolved to single definition in a file.
Workspace symbol lookup (Ctrl+p followed by #) is using ctags from what I've seen (https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/workspaceSymbols/provider.ts/)

So my idea was to run workspace-symbol-lookup, [filter out results](https://github.com/DonJayamanne/pythonVSCode/pull/1032/files#diff-79743517e0ea50ece0977491944dc315R36) a bit, and display choices to user in a quick-pick menu. Instead of workspace-symbol-lookup it is sure possible to use different library, but I believe this functionality can be reused.

**Comment by skyjur** [comment]
I realised something just now, which I didn't know before, Workspace-Symbol-Lookup is not limited to python files. So I will need to fix this in one of the ways:

1) add filtering by file type
2) call [WorkspaceSymbolProvider](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/workspaceSymbols/provider.ts/) directly
3) use iresolve (If i find that it works) instead of ctags

However, I still think that workspace-symbol-lookup and auto-import should use same underlying library.

**Comment by skyjur** [comment]
Sorry if I am misleading with the terminology that I used.

I am not sure if I correctly use these terms: 

"symbol-lookup", for to the jedi powered lookup of symbol in currently open file, under the cursor

"workspace-symbol-lookup" symbol search across all workspace files which is available through `Ctrl+P` followed by `#`

**Comment by dhensen** [comment]
I'm on 0.7.0 now, but I dont see this option when I open the Command Pallette and type autoimport... How does this work? Do I need to enable something?

**Comment by DonJayamanne** [comment]
Unfortunately this feature is not available in the extension.

**Comment by JGH1000** [comment]
Perhaps it would be much easier to use an extension for autoimports, importmagic does exactly that:
https://github.com/alecthomas/importmagic

**Comment by bluehezihhh** [comment]
How do I use this feature? When I try to use it , this error occurs.
`Running the contributed command:'python.autoImportAtCursor' failed.`
image

 What should I do? Thank you very much

**Comment by skyjur** [comment]
@bluehezihhh could you provide more information, in what setup/when you run it, and if there was any stack-trace?

**Comment by bluehezihhh** [comment]
I do it on windows10,and this is my path.
image

I can run "python" and "ctags" command in cmd. And I set as this 
image
But when I select impotr like this,I can not find it
image
finally I press "alt+enter" when Cursor at "sys" like this
image
but I can't find any information about the warning. what should I do? Thank you very much!

**Comment by skyjur** [comment]
I'm afraid this will not work on 'sys', because symbols are looked up only in ctags file currently. So it won't work with modules `import x` and only works with `from x import y`.

It looks like https://github.com/alecthomas/importmagic that was mentioned here could do much better job than the current implementation with ctags. Woud be happy to give a go but at the moment I'm quite busy so unfortunately can't contribute much.

**Comment by bluehezihhh** [comment]
Thanks a lot

**Comment by ferdynice** [comment]
If I'm correct this feature is currently present in vscode 0.7 but not enabled/working. I also get "Running the command failed" error when I map the command to a shortcut.

I believe a feature like this is one of the last things that will stop people from switching from fully-fledged IDEs like PyCharm. It just saves a ton of time to manually lookup and type imports. Also most required parts for this functionality is already present, like project symbols.

**Pull request merged**
