### PR TITLE
fix #1296 ability to opt out of telemetry using vscode settings

### LINKED ISSUE #1296: Add ability to opt out of Telemetry reporting

### PR DESCRIPTION
**Pull request by DonJayamanne**

### CODE REVIEW

**Comment by brettcannon** [comment]
Reading the description for [vscode-extension-telemetry](https://www.npmjs.com/package/vscode-extension-telemetry), it seems the extension already does the right thing when the global flag is flipped. So maybe this wasn't needed after all?

**Comment by DonJayamanne** [comment]
Lol, there are others out there that have their own flags. Feel like an idiot for not seeing this.

**Comment by DonJayamanne** [comment]
Will remove this when we I work on telemetry.

**Comment by brettcannon** [comment]
Hey, I didn't know either until I was trying to figure out how extensions specify the App Insights flag.

**Pull request merged**
