### PR TITLE
WIP/ PyDev debugger bridge.

### PR DESCRIPTION
**Pull request by xoviat**
Not yet finished, but simply here for comments and feedback.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
Wow, thanks

**Comment by DonJayamanne** [comment]
Please make the changes so that, you don't blue away existing code. Instead add your code as a separate solution (implementation). This way when debugging we can provide both debuggers and people can choose. Once this is proven to be stable we can make the existing code obsolete.

**Comment by DonJayamanne** [comment]
That's ok, please ignore my previous comments. I will move the files around. You can carry on, easier for you.

**Comment by xoviat** [comment]
> Please make the changes so that, you don't blue away existing code. Instead add your code as a separate solution (implementation). This way when debugging we can provide both debuggers and people can choose. Once this is proven to be stable we can make the existing code obsolete.

That's the plan. The only change that breaks exisiting functionality is line 69 of LocalDebugClient.ts.

**Comment by xoviat** [comment]
Unfortunately, I have run into some considerable problems that necessitate far more work than I expected. As such, I am closing this pull request for now and it is doubtful whether I will finish this.

**Comment by DonJayamanne** [comment]
Thanks for the effort.

**Pull request closed without merging**
