### PR TITLE
CodeLens for Shebangs

### PR DESCRIPTION
**Pull request by Kavakuo**
This implements #1261 and works best in combination with #1263 (otherwise clicking the CodeLens without an error is only possible with an opened workspace).

The CodeLens is only visible when the current selected interpreter is another than the interpreter specified in the shebang. Clicking the CodeLens changes the interpreter and after that the CodeLens disappears.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@Kavakuo 
Thanks for the PR, overall its fine apart from a few minor issues. One last thing I'd like for you to add are some unit tests.

**Comment by DonJayamanne** [comment]
@Kavakuo 
I have merged some fixes to the unit tests into the master branch. Please merge the master into your branch. This will help with the testing on [travis](https://travis-ci.org/DonJayamanne/pythonVSCode).

**Comment by DonJayamanne** [comment]
@Kavakuo let me know if you need a hand with the unit tests.
Just have a look at the existing unit tests where I'm opening a local file and running the tests.
FYI - To speed up the tests you could delete some of the test directories (e.g. jupyter, common, linters, formatting, etc) - but don't commit those.

**Comment by Kavakuo** [comment]
I think I made it 👍 I hope these tests are ok and the files I added are in the right place. 
To run only a few tests I discovered the very helpful `grep` option for the testrunner configuration. Set it to "Shebang" to run my tests.

**Comment by Kavakuo** [comment]
@DonJayamanne Everything fixed. Travis also passes 👍

**Comment by DonJayamanne** [comment]
@Kavakuo , please could you use ```async``` ```await``` everywhere in your tests.
There are other issues that haven't been completed, please have a look at my comments.

**Comment by Kavakuo** [comment]
@DonJayamanne 
Thanks for the hint to use `async` and `await`. I'm fairly inexperienced with typescript/nodejs. You mentioned before that there are other issues, but I think you forgot to list them.

> @Kavakuo
Thanks for the PR, overall its fine apart from a few minor issues. One last thing I'd like for you to add are some unit tests.

**Comment by DonJayamanne** [comment]
@Kavakuo thanks for the PR.

**Comment by Kavakuo** [comment]
@DonJayamanne 
Thanks for merging and appreciating my ideas. If there are any problems in the future with my code, just let me know. It was my pleasure to contribute to this project!

**Comment by brettcannon** [comment]
One thing I just realized is what happens if someone uses `env`, e.g. `#!/usr/bin/env python`?

**Comment by Kavakuo** [comment]
Oh well, I think that won't work currently. Totally overseen this, because I usually use absolute paths. The extension would want to set `/usr/bin/env python` as `python.pythonPath` and detects that this is an invalid interpreter... 🤔 So there is currently also no support in general for setting `python.pythonPath` something that starts with `/usr/bin/env`.

I think the best solution is to build something that resolves the raw `python.pythonPath` value startung with `/usr/bin/env` to an absolute path before setting the interpreter. This would bring full support for `/usr/bin/env` values in the settings and it would be easy to resolve the shebang before showing the CodeLens as well.

Can look into this tomorrow. If you have other solution ideas or want to build this yourself, let me know. Should we open a new issue for this?

**Comment by brettcannon** [comment]
Yeah, an issue would be good and I have no specific suggestions on how best to handle it.

**Comment by DonJayamanne** [comment]
I can fix that, basically i just evaluate the expression and get the path out of that.

**Pull request merged**
